---
# Network name on CloudStack
network: "vnet-kubcluster"
# Zone name in which the network and nodes are created    
zone: "ZUERICH_IX"
# Template for the Nodes            
template: "AlmaLinux 9"
# Service offering on CloudStack       
offering: "2cpu_4gb"
# SRG and SWISS TXT public ip ranges          
cidrs: "['146.159.0.0/16','185.27.109.19/32','147.161.128.0/17']"
# Variable for path of this File                     
vars_file_path: "{{ playbook_dir }}/../hosts/group_vars/all/vars.yml"
# Outbound SSH ports
master_port: 2222             
worker1_port: 2223
worker2_port: 2224
kubeapi_port: 6443
# Loadbalancer Rules for kubernetes
loadbalancer_http: "http-loadbalancer-workers"
loadbalancer_https: "https-loadbalancer-workers"
# Algorithm for loadbalancer
loadbalancer_algorithm: "roundrobin"
# Name for kubernetes user
kubernetes_user: "kube"
# Automatically created and changed variables DO NOT CHANGE
natip: "185.27.109.29"
worker1_local_ip: "10.1.1.212"
master_local_ip: "10.1.1.95"
worker2_local_ip: "10.1.1.237"
cluster_joincommand: "sudo kubeadm join 10.1.1.95:6443 --token mrjolg.9wwn1c8vnc3o0ozx --discovery-token-ca-cert-hash sha256:af3bd72d65b6d3ea5228999dbca322241172e47d9ec36c5b95d3e47e131c448f "
